services:
  queenbee:
    container_name: queenbee
    image: queenbee
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8050:3000'
    env_file:
      - .env
