services:
  queenbee:
    container_name: queenbee
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - BASE_URL=https://queenbee-api.login.no/v1
      - TYPE=testmain
      - PROJECT_ID: ${PROJECT_ID}
      - PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
      - PRIVATE_KEY: ${PRIVATE_KEY}
      - CLIENT_EMAIL: ${CLIENT_EMAIL}
      - CLIENT_ID: ${CLIENT_ID}
      - AUTH_URI: ${AUTH_URI}
      - TOKEN_URI: ${TOKEN_URI}
      - AUTH_CERT_URL: ${AUTH_CERT_URL}
      - CLIENT_CERT_URL: ${CLIENT_CERT_URL}
      - UNIVERSE_DOMAIN: ${UNIVERSE_DOMAIN}
      - GITLAB_MESSAGE: ${GITLAB_MESSAGE}
      - CDN_URL=https://cdn.login.no
