# Node image with Alpine Linux
FROM node:20-alpine

# Arguments
ARG GITLAB_MESSAGE
ARG API_URL
ARG NEXT_PUBLIC_BROWSER_API
ARG TYPE
ARG PROJECT_ID
ARG PRIVATE_KEY_ID
ARG PRIVATE_KEY
ARG CLIENT_EMAIL
ARG CLIENT_ID
ARG AUTH_URI
ARG TOKEN_URI
ARG AUTH_CERT_URL
ARG CLIENT_CERT_URL
ARG UNIVERSE_DOMAIN
ARG GITLAB_MESSAGE
ARG CDN_URL
ARG NEXT_PUBLIC_TEKKOM_BOT_API_URL

# Env
ENV GITLAB_MESSAGE=$GITLAB_MESSAGE
ENV API_URL=$API_URL
ENV NEXT_PUBLIC_BROWSER_API=$NEXT_PUBLIC_BROWSER_API
ENV TYPE=$TYPE
ENV PROJECT_ID=$PROJECT_ID
ENV PRIVATE_KEY_ID=$PRIVATE_KEY_ID
ENV PRIVATE_KEY=$PRIVATE_KEY
ENV CLIENT_EMAIL=$CLIENT_EMAIL
ENV CLIENT_ID=$CLIENT_ID
ENV AUTH_URI=$AUTH_URI
ENV TOKEN_URI=$TOKEN_URI
ENV AUTH_CERT_URL=$AUTH_CERT_URL
ENV CLIENT_CERT_URL=$CLIENT_CERT_URL
ENV UNIVERSE_DOMAIN=$UNIVERSE_DOMAIN
ENV GITLAB_MESSAGE=$GITLAB_MESSAGE
ENV CDN_URL="https://cdn.login.no"
ENV NEXT_PUBLIC_TEKKOM_BOT_API_URL

# Workdir
WORKDIR /app

# Copies package.json and package-lock.json
COPY package*.json ./

# Installs dependencies
RUN npm install

# Copies the rest of the UI source code
COPY . .

RUN npm run build

# Exposes port 3000
EXPOSE 3000

CMD npm start
