services:
  queenbee:
    container_name: queenbee
    image: queenbee
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:3000'
    env_file:
      - .env
    networks:
      - workerbee_default
    mem_limit: 1g
    cpus: "2.0"
    dns:
      - 8.8.8.8
      - 1.1.1.1
      - 10.177.195.1
      - 213.186.33.99

networks:
  workerbee_default:
    external: true
